version = 1

exclude_patterns = [
  ".env.local",
  ".env.*.local",
  "npm-debug.log*",
  "yarn-debug.log*",
  "yarn-error.log*",
  "pnpm-debug.log*",
  ".idea",
  ".vscode",
  "*.suo",
  "*.ntvs*",
  "*.njsproj",
  "*.sln",
  "*.sw?"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["vue"]

[[transformers]]
name = "prettier"
enabled = true